config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  resources :books
  resources :users
  get 'home/about' => 'homes#about', as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, length: {minimum: 2,maximum: 20}, uniqueness: true
  validates :introduction,length: {maximum: 50}

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(_resource)
      user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to "/books"
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.user == current_user
       book.destroy
       flash[:notice] = "Book was successfully destroyed."
       redirect_to '/books'
    else
       render "index"
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @book = Book.new 
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
     if @user == current_user
      render "edit"
     else
      redirect_to user_path(current_user)
     end
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
   else
      render :edit
   end
  end
    
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div>
   <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
<div>
<table class="table">
  <tbody>
    <tr>
    </tr>
    <tr>
      <th>name</th>
      <th><%=user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%=user.introduction %></th>
    </tr>
  </tbody>
</table>
</div>
<div>
<% if user == current_user %>
<%end%>

<%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
<i class="fa-solid fas fa-user-cog"></i>
<%end%>
</div>

<h1>New book</h1>

<%= form_with model: book do |f| %>
<div class="form-group">
<h4>Title</h4>
<%= f.text_field :title %>
</div>

<div class="form-group">
<h4>Opinion</h4>
<%= f.text_area :body %>
</div>

<div class="form-group">
<%= f.submit "Create Book",class:"btn btn-success"%>
</div>
<% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
<h1>Editing Book</h1>
    <% if @book.errors.any? %>
  　<h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
  　<ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  　</ul>
　　<% end %>
　
<%= form_with model:@book, url:book_path(@book.id), method: :patch do |f| %>
 <div class="form-group">
 <label for="book_title">Title</label>
 <%= f.text_field :title, class:"form-control book_title", autofocus: true, id:"book_title" %>
 </div>
 <div class="form-group">
 <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, class:"form-control book_body", autofocus: true, id:"book_body" %>
 </div>
 <div>
 <%= f.submit "Update Book",class:"btn btn-success" %>
</div>
<% end %>
<%=link_to "Show",book_path(@book.id) %>
|
<%=link_to "Back",books_path %>
</div>
</div>
</div>
</div>
  

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    <% if @book.errors.any? %>
  　<h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
  　<ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  　</ul>
　　<% end %>
  <div class="row">
    <div class="col-md-3">

      <%= render 'list', book: @book, user: current_user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
       <table class="table table-hover table-inverse">
        <thead>
        <tr>
          <th></th>
          <th>Title </th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
        <% @books.each do |book| %>
          <tr>
           <td>
            <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
            <%end%>
           </td>
            <td>
             <%= link_to book.title,book_path(book) %>
            </td>
            <td>
             <%= book.body %>
            </td>
             <td colspan="3">
             </td>
           </tr>
          </thead>
           <%end%>
        </table>  
        </div>
      </div>
    </div>
   

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'list', book: @book_new ,user: @user %>
    </div>

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      <tr>
        <td>
        <%= image_tag @book.user.get_profile_image(100,100) %>
         <p><%=link_to @book.user.name,user_path(@book.user) %></p>
        </td>
         <td><%=link_to @book.title,book_path(@book.id) %></td>
         <td><%= @book.body%></td>
         <td>
          <% if @book.user == current_user %>
          <%=link_to edit_book_path(@book.id), class:"btn btn-sm btn-success" do %>
          Edit
          <%end%>
          <%end%>
         </td>
         <td>
          <% if @book.user == current_user %>
          <%=link_to book_path(@book.id), method: :delete, "data-confirm" => "Are you sure?", class:"btn btn-sm btn-danger" do %>
          Destroy
          <%end%>
          <%end%>
         </td>
      </tr>
    </tbody>
  </table>
 </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
        Welcome to <i class="fa-solid fas fa-book"></i><strong>Bookers</strong>!</h1>

app/views/homes/top.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>welcome to <i class="fa-solid fas fa-book"></i><strong>Bookers</strong> !!</h1>
<p>In <i class="fa-solid fas fa-book"></i><strong>Bookers</strong>,</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>
<div class="btn-wrapper col-10 mx-auto">
 <div>
  <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
 </div>
  <div>
  <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign-up" %>
 </div>
 </div>
 </div>
 </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/2f39ed21ce.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <header>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to user_path(current_user), class:'nav-link text-light' do %>
        <i class='fa-solid fas fa-home'></i>
        Home
        <% end %>
      </li>
       <li class="nav-item">
        <%= link_to users_path, class:'nav-link text-light' do %>
        <i class='fa-solid fas fa-users'></i>
        Users
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to books_path, class:'nav-link text-light' do %>
        <i class='fa-solid fas fa-book-open'></i>
        Books
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class:'nav-link text-light' do %>
        <i class='fa-solid fas fa-sign-out-alt'></i>
        Log out
        <% end %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to root_path, class:'nav-link text-light' do %>
        <i class='fa-solid fas fa-home'></i>
        Home
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to about_path,class: 'nav-link text-light' do %>
        <i class='fa-solid fas fa-link'></i>
        About
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
        <i class='fa-solid fas fa-user-plus'></i>
        Sign up
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
        <i class='fa-solid fas fa-sign-in-alt'></i>
        Log in
        <% end %>
      </li>
    <% end %>
    </ul>
          </div>
        </div>
      </nav>
  </header>
  <main class="mb-auto">
  <% flash.each do |message_type, message| %>
   <%=content_tag(:div, message,class:message_type)%>
  <%end%>
    <%= yield %>
  </main>
  
  <footer>
    <div class="container mt-5">
      <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
    </div
   </footer>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
<h2>User info</h2>
    <% if @user.errors.any? %>
  　<h3><%= @user.errors.count %>　error prohibited this obj from being saved:</h3>
  　<ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  　</ul>
　　<% end %>
<%= form_with model: @user do |f| %>
 <div class="form-group">
 <label for="user_name">Name</label>
 <%= f.text_field :name, class:"form-control name", autofocus: true, id:"user_name" %>
 </div>
 <div class="form-group">
 <label for="user_image">Image</label>
 <%= f.file_field :profile_image,class:"form-control-file user_image", id:"user_profile_image", accept:"image/*" %> 
 </div>
 <div class="form-group">
 <label for="user_Introduction">Introduction</label>
  <%= f.text_area :introduction, class:"form-control introduction", autofocus: true, id:"user_introduction"%>
 </div>
 <div>
 <%= f.submit "Update User",class:"btn btn-secondary" %>
</div>
  
  
  <% end %>
  

app/views/users/index.html.erb
 <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', book: @book, user: current_user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
       <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th colspan="3"></th>
        </tr>
          <% @users.each do |user| %>
        <tr>
           <td>
              <%= image_tag user.get_profile_image(100,100) %>
           </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to"Show",user_path(user.id) %>
            </td>
             <td colspan="3">
             </td>
          </tr>
       </thead>
     <%end%>
    </table>  
    </div> 
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
       <%= render 'books/list', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
  　　　　　<h2>Books</h2>
   　　　　　<table class="table table-hover table-inverse">
        　<thead>
        　　<tr>
          　<th></th>
          　<th>Title </th>
          　<th>Opinion</th>
          　<th colspan="3"></th>
        　　</tr>
        <% @books.each do |book| %>
          <tr>
           <td>
            <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
            <%end%>
           </td>
            <td>
              <%=link_to book.title,book_path(book) %>
            </td>
            <td>
             <%= book.body %>
            </td>
             <td colspan="3">
             </td>
           </tr>
          </thead>
           <%end%>
        </table>  
 　   　 </div>
 </div>
</div> 